version: "3.9"
services:
  redis:
    image: "redis:alpine"
    networks:
      - alticciappredis-net
    hostname: redis
    ports:
      - "6379:6379"
  server:
    image: alticci-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      - spring.redis.host=redis
      - spring.redis.port=6379
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    networks:
      - alticciappredis-net
    depends_on:
      - redis
    restart: on-failure
networks:
  alticciappredis-net: